debug in docker

diff --git a/packages/app/.release/Dockerfile b/packages/app/.release/Dockerfile
--- a/packages/app/.release/Dockerfile
+++ b/packages/app/.release/Dockerfile
@@ -5,8 +5,8 @@ WORKDIR /app
 COPY . .
 
 # Debug step: output what's been copied
-# RUN echo "✅ Contents of /app after COPY:" && ls -alh /app && \
-#     echo "📁 Contents of /app/build:" && ls -alh /app/build || echo "❌ build/ missing"
+RUN echo "✅ Contents of /app after COPY:" && ls -alh /app && \
+    echo "📁 Contents of /app/build:" && ls -alh /app/build || echo "❌ build/ missing"
 
 # # Copy in prebuilt files
 # COPY build          ./build
